root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/manager_bin"
  cmd = "go build -o ./tmp/manager_bin ./cmd/manager/main.go"
  delay = 1000
  exclude_dir = ["tmp"]
  include_dir = ["cmd/manager", "internal", "pkg"]
  include_ext = ["go"]
  send_interrupt = true

[log]
  time = false

[color]
  main = "blue"
